[tools]
go = "1.26"
golangci-lint = "2.12.2"

[env]
GOOS = "linux"
GOARCH = "amd64"
CGO_ENABLED = "0"

[tasks.default]
run = [
    { task = "modules" },
    { task = "build" },
    { task = "lint" },
]

[tasks.modules]
run = "go mod tidy"

[tasks.build]
run = "go build -trimpath -v -o /dev/null ./..."

[tasks.lint]
run = "golangci-lint run"
