[tools]
go = "1.26"
golangci-lint = "2.12.2"

[env]
GOOS = "linux"
GOARCH = "amd64"
CGO_ENABLED = "0"

[tasks.default]
run = [
    { task = "build" },
    { task = "check" },
]

[tasks.modules]
run = "go mod download"

[tasks.tidy]
run = "go mod tidy"

[tasks.build]
depends = [ "modules" ]
run = "go build -trimpath -v -o /dev/null ./..."

[tasks.check]
depends = [ "lint", "test" ]

[tasks.lint]
run = "golangci-lint run"

[tasks.test]
run = "go test ./..."
